### ISSUE TITLE
scion在mac跑不起来

### ISSUE THREAD

**Issue by blueIce525** [jrainlau/scion#2]
hi,我用命令安装npm install scion-cli -g
然后输入 scion add，提示的是 node: bad option: --harmony
是什么原因跑不起来呢？

安装时候提示 /usr/local/bin/scion -> /usr/local/lib/node_modules/scion-cli/bin/scion
/usr/local/lib
是不是这一行有错误 #!/usr/bin/env node --harmony

**Comment by jrainlau** [comment]
应该是，有时间再弄。。。

**Comment by jrainlau** [comment]
新版的scion完美支持`MacOS`系统哦！

**Comment by ChenJiaH** [comment]
@jrainlau 想请教一下mac跑不起来的原因是什么呢，请问是哪个commit解决来这个问题呀？感谢

**Comment by jrainlau** [comment]
现在能跑啊。原因是旧版是用老的Node写法写的，和新的Node不兼容所致
