### ISSUE TITLE
没看懂怎么用，git地址在哪填写呢？

### ISSUE THREAD

**Issue by coderzzp** [jrainlau/scion#3]

**Comment by jrainlau** [comment]
![image](https://user-images.githubusercontent.com/12172868/30532137-4201e3b8-9c18-11e7-8615-5ae35d486b99.png)

这里

**Comment by coderzzp** [comment]
我是说templates.json文件的的模板里面：{"myvue":{"owner/name":"zzp","branch":"master"}}是一个模板，但是git地址在哪里在哪里填写呢？

**Comment by jrainlau** [comment]
填owner/name就行了。scion不是根据git地址来下载仓库代码的。比如本仓库的owner/name就是`jrainlau/scion`，写这个即可，具体你可以看源码，readme里也有写

**Comment by coderzzp** [comment]
感谢！
