### ISSUE TITLE
请问远程仓库的template模板的代码一般是什么样的？

### ISSUE THREAD

**Issue by leeboya** [jrainlau/scion#7]
> 通过选择不同的模版，SCION会自动从远程仓库把相应的模板拉取到本地，完成项目的搭建。

请问这里的 **远程仓库模板** 一般是长什么样的？

**Comment by alanchenchen** [comment]
能搭建项目的最简单目录结构，比如使用webpack搭建的话，就是一个完整的webpack目录和配置文件， @leeboya 比如我的一个模板长这个样子，[simple-template](https://github.com/alanchenchen/simple-template)

**Comment by leeboya** [comment]
好的，谢谢您了！我再观摩观摩你的模板
