### ISSUE TITLE
请教个问题，为什么我自定义的命令行，执行后是用编辑器打开该文件了？

### ISSUE THREAD

**Issue by yaotaiye** [jrainlau/scion#9]
代码：
package.json:
...
 "bin": {
    "wtycli": "./bin/index.js"
  },
...
index.js:
console.log("test")
执行步骤：
1.  npm link

2.  wtycli
结果：
没有运行文件，而是直接用编辑器打开了该文件（index.js）。。。

**Comment by jrainlau** [comment]
1. 去掉 .js 后缀
2. 文件头加入 `#!/usr/bin/env node`
